DROP TABLE `attributes`;--> statement-breakpoint
DROP TABLE `attribute_values`;--> statement-breakpoint
DROP TABLE `categories`;--> statement-breakpoint
DROP TABLE `categoriesToPosts`;--> statement-breakpoint
DROP TABLE `countries`;--> statement-breakpoint
DROP TABLE `coupons`;--> statement-breakpoint
DROP TABLE `gallery`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `orders`;--> statement-breakpoint
DROP TABLE `order_items`;--> statement-breakpoint
DROP TABLE `order_statuses`;--> statement-breakpoint
DROP TABLE `products`;--> statement-breakpoint
DROP TABLE `product_attributes`;--> statement-breakpoint
DROP TABLE `product_attribute_values`;--> statement-breakpoint
DROP TABLE `product_categories`;--> statement-breakpoint
DROP TABLE `product_coupons`;--> statement-breakpoint
DROP TABLE `product_shipping_info`;--> statement-breakpoint
DROP TABLE `product_suppliers`;--> statement-breakpoint
DROP TABLE `product_tags`;--> statement-breakpoint
DROP TABLE `sells`;--> statement-breakpoint
DROP TABLE `shipping_country_zones`;--> statement-breakpoint
DROP TABLE `shipping_rates`;--> statement-breakpoint
DROP TABLE `shipping_zones`;--> statement-breakpoint
DROP TABLE `slideshows`;--> statement-breakpoint
DROP TABLE `suppliers`;--> statement-breakpoint
DROP TABLE `tags`;--> statement-breakpoint
DROP TABLE `variants`;--> statement-breakpoint
DROP TABLE `variant_options`;--> statement-breakpoint
DROP TABLE `variant_values`;