ALTER TABLE attributes ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE attributes ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE attribute_values ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE attribute_values ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE countries ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE countries ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE coupons ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE coupons ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE gallery ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE gallery ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE notifications ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE notifications ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE orders ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE orders ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE order_items ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE order_items ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE order_statuses ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE order_statuses ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE products ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE products ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_attributes ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_attributes ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_attribute_values ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_attribute_values ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_categories ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_categories ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_coupons ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_coupons ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_shipping_info ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_shipping_info ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_suppliers ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_suppliers ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE product_tags ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE product_tags ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE shipping_country_zones ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE shipping_country_zones ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE shipping_rates ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE shipping_rates ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE shipping_zones ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE shipping_zones ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE slideshows ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE slideshows ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE suppliers ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE suppliers ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE variants ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE variants ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE variant_options ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE variant_options ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE variant_values ADD `createdOn` integer;--> statement-breakpoint
ALTER TABLE variant_values ADD `updatedOn` integer;--> statement-breakpoint
ALTER TABLE `coupons` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `coupons` DROP COLUMN `updated_at`;--> statement-breakpoint
ALTER TABLE `gallery` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `gallery` DROP COLUMN `updated_at`;--> statement-breakpoint
ALTER TABLE `orders` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `order_statuses` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `order_statuses` DROP COLUMN `updated_at`;--> statement-breakpoint
ALTER TABLE `order_statuses` DROP COLUMN `updated_by`;--> statement-breakpoint
ALTER TABLE `products` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `products` DROP COLUMN `updated_at`;--> statement-breakpoint
ALTER TABLE `shipping_zones` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `shipping_zones` DROP COLUMN `updated_at`;--> statement-breakpoint
ALTER TABLE `shipping_zones` DROP COLUMN `created_by`;--> statement-breakpoint
ALTER TABLE `shipping_zones` DROP COLUMN `updated_by`;--> statement-breakpoint
ALTER TABLE `suppliers` DROP COLUMN `created_at`;--> statement-breakpoint
ALTER TABLE `suppliers` DROP COLUMN `updated_at`;